environment:
  matrix:
    - NODE_VERSION: 18
      platform: x64

shallow_clone: true

services:
  - postgresql94

install:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=C:\Program Files\PostgreSQL\9.4\bin\;%PATH%
  - ps: Install-Product node $env:NODE_VERSION $env:platform
  - node -v
  - node -e "console.log(process.argv,process.execPath,process.arch)"
  - npm -v
  - npm install --fallback-to-build=false
  - python test\check_shared_libs.py .\
  - npm ls
  - npm test

build: OFF
test: OFF
deploy: OFF
